version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: accounts
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_URL: "postgres://user:password@db:5432/accounts?sslmode=disable"
      ENV: local
    ports:
      - "8080:8080"

volumes:
  postgres_data:
